version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y zip
      - apt-get install -y awscli
    finally:
      - echo This always runs even if the update or install command fails 

  build:
    commands:
      - echo Entered the build phase...
      - |
        for function_dir in lambda/*; do
          if "$CODEBUILD_SRC_DIR/$function_dir/lambda_test.py" -nt "$CODEBUILD_SRC_DIR/$function_dir/lambda_test.py"; then
            chmod -R o+rX .
            cd $function_dir && zip lambda_test.zip lambda_test.py
            chmod -R o+rX .
            chmod -r 400 lambda_test.zip
            aws s3 cp lambda_test.zip s3://test-lambda-code-1/$(basename $function_dir)/lambda_test.zip
            aws lambda update-function-code --function-name arn:aws:lambda:ap-south-1:474532148129:function:test --s3-bucket test-lambda-code-1 --s3-key $(basename $function_dir)/lambda_test.zip
          else
            echo Skipping build for function $(basename $function_dir) because there were no changes to the code
          fi
        done
    finally:
      - echo Installation Completed...

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`  