version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y zip
      - apt-get install -y awscli
    finally:
      - echo This always runs even if the update or install command fails 

  build:
    commands:
      - echo Entered the build phase...
      - echo $LAMBDA_CODE_DIR
      - cd $LAMBDA_CODE_DIR && zip -r /$LAMBDA_CODE_DIR.zip *
      - ls 
      - aws s3 cp ../$LAMBDA_CODE_DIR.zip s3://$S3_BUCKET/$S3_KEY_PREFIX/$LAMBDA_CODE_DIR/$LAMBDA_CODE_DIR.zip
      - aws lambda update-function-code --function-name arn:aws:lambda:us-east-1:287882505924:function:test --s3-bucket $S3_BUCKET --s3-key $S3_KEY_PREFIX/$LAMBDA_CODE_DIR/$LAMBDA_CODE_DIR.zip
    finally:
      - echo Installation Completed...

  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`

