version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y zip
      - apt-get install -y awscli
    finally:
      - echo This always runs even if the update or install command fails 

  build:
    commands:
      - echo Entered the build phase...
      - cd lambda/function-1 && zip test.zip test.py
      - ls 
      - aws s3 cp test.zip s3://krny-lambda-code/function-1/test.zip
      - aws lambda update-function-code --function-name  arn:aws:lambda:us-east-1:287882505924:function:test --s3-bucket krny-lambda-code --s3-key function-1/test.zip
    finally:
      - echo Installation Completed...
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`